# Generated by Django 5.1.7 on 2025-03-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
