# Generated by Django 5.1.7 on 2025-03-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='images/default/', null=True, upload_to='images/'),
        ),
    ]
