# Generated by Django 5.1.7 on 2025-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(default='default/image.png', upload_to='images'),
        ),
    ]
