# Generated by Django 5.0.6 on 2025-03-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_employee_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.ImageField(default='default/image.png', upload_to='images/'),
        ),
    ]
