# Generated by Django 5.0.6 on 2025-03-21 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_employee_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comp_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 16, 25, 32, 699361, tzinfo=datetime.timezone.utc)),
        ),
    ]
