# Generated by Django 5.1.7 on 2025-03-25 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_employee_comp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 16, 48, 36, 534988, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='departments',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 16, 48, 36, 534988, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='comp_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 16, 48, 36, 534988, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 16, 48, 36, 534988, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 16, 48, 36, 534988, tzinfo=datetime.timezone.utc)),
        ),
    ]
